//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.CMS.Administration.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.CMS.Administration.Core.Resources.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        internal static string Licensing {
            get {
                return ResourceManager.GetString("Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string MainContent {
            get {
                return ResourceManager.GetString("MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string MainContentContent {
            get {
                return ResourceManager.GetString("MainContentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Content.
        /// </summary>
        internal static string MainContentMediaContent {
            get {
                return ResourceManager.GetString("MainContentMediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainContentMenu {
            get {
                return ResourceManager.GetString("MainContentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy.
        /// </summary>
        internal static string MainContentTaxonomy {
            get {
                return ResourceManager.GetString("MainContentTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        internal static string MainDashboardCMS {
            get {
                return ResourceManager.GetString("MainDashboardCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        internal static string MainDashboards {
            get {
                return ResourceManager.GetString("MainDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string MainDashboardServer {
            get {
                return ResourceManager.GetString("MainDashboardServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string MainReporting {
            get {
                return ResourceManager.GetString("MainReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Definitions.
        /// </summary>
        internal static string MainReportingDefinitions {
            get {
                return ResourceManager.GetString("MainReportingDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Scheduler.
        /// </summary>
        internal static string MainReportingScheduler {
            get {
                return ResourceManager.GetString("MainReportingScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string MainSettingsConfiguration {
            get {
                return ResourceManager.GetString("MainSettingsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string MainSettingsConfigurationCache {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Content Types.
        /// </summary>
        internal static string MainSettingsConfigurationContentTypes {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        internal static string MainSettingsConfigurationLanguageSettings {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data Fields.
        /// </summary>
        internal static string MainSettingsConfigurationMetaData {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string MainSettingsConfigurationPermissions {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string MainSettingsConfigurationTemplates {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string MainSettingsConfigurationUserManagement {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Types.
        /// </summary>
        internal static string MainSettingsConfigurationUserManagementProfileTypes {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationUserManagementProfileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MainSettingsConfigurationUserManagementUsers {
            get {
                return ResourceManager.GetString("MainSettingsConfigurationUserManagementUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string MainSupport {
            get {
                return ResourceManager.GetString("MainSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Doc.
        /// </summary>
        internal static string MainSupportAssemblyDoc {
            get {
                return ResourceManager.GetString("MainSupportAssemblyDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngularJs Doc.
        /// </summary>
        internal static string MainSupportJsDoc {
            get {
                return ResourceManager.GetString("MainSupportJsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Logic Doc.
        /// </summary>
        internal static string MainSupportTsDoc {
            get {
                return ResourceManager.GetString("MainSupportTsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApi.
        /// </summary>
        internal static string MainSupportWsDoc {
            get {
                return ResourceManager.GetString("MainSupportWsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seconds.
        /// </summary>
        internal static string ServerDashboardRefresh {
            get {
                return ResourceManager.GetString("ServerDashboardRefresh", resourceCulture);
            }
        }
    }
}
