//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.CMS.Administration.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.CMS.Administration.Core.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Completed.
        /// </summary>
        internal static string ActionCompleted {
            get {
                return ResourceManager.GetString("ActionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is not completed.
        /// </summary>
        internal static string ActionNotCompleted {
            get {
                return ResourceManager.GetString("ActionNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new connection.
        /// </summary>
        internal static string AddConnection {
            get {
                return ResourceManager.GetString("AddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content.
        /// </summary>
        internal static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content Type.
        /// </summary>
        internal static string AddContentType {
            get {
                return ResourceManager.GetString("AddContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Media Content.
        /// </summary>
        internal static string AddMediaContent {
            get {
                return ResourceManager.GetString("AddMediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu.
        /// </summary>
        internal static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meta Data Field.
        /// </summary>
        internal static string AddMetaDataField {
            get {
                return ResourceManager.GetString("AddMetaDataField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile Type.
        /// </summary>
        internal static string AddProfileType {
            get {
                return ResourceManager.GetString("AddProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report Scheduler.
        /// </summary>
        internal static string AddReportScheduler {
            get {
                return ResourceManager.GetString("AddReportScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Taxonomy.
        /// </summary>
        internal static string AddTaxonomy {
            get {
                return ResourceManager.GetString("AddTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        internal static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your alias, are you sure you want to continue?.
        /// </summary>
        internal static string AliasNotFinished {
            get {
                return ResourceManager.GetString("AliasNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Content.
        /// </summary>
        internal static string CMSContent {
            get {
                return ResourceManager.GetString("CMSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, {0}.
        /// </summary>
        internal static string CMSDashboard {
            get {
                return ResourceManager.GetString("CMSDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents List.
        /// </summary>
        internal static string ContentsList {
            get {
                return ResourceManager.GetString("ContentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type Editor.
        /// </summary>
        internal static string ContentTypeEditor {
            get {
                return ResourceManager.GetString("ContentTypeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your content type, are you sure you want to continue?.
        /// </summary>
        internal static string ContentTypeNotFinished {
            get {
                return ResourceManager.GetString("ContentTypeNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type Preview.
        /// </summary>
        internal static string ContentTypePreview {
            get {
                return ResourceManager.GetString("ContentTypePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type Editor.
        /// </summary>
        internal static string ContentTypesEdit {
            get {
                return ResourceManager.GetString("ContentTypesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type list.
        /// </summary>
        internal static string ContentTypesList {
            get {
                return ResourceManager.GetString("ContentTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your content type and your folder template, are you sure you want to continue?.
        /// </summary>
        internal static string ContentTypeTemplateNotFinished {
            get {
                return ResourceManager.GetString("ContentTypeTemplateNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is already in use!.
        /// </summary>
        internal static string DuplicateAlias {
            get {
                return ResourceManager.GetString("DuplicateAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing connection.
        /// </summary>
        internal static string EditConnection {
            get {
                return ResourceManager.GetString("EditConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Content.
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Content Type.
        /// </summary>
        internal static string EditContentType {
            get {
                return ResourceManager.GetString("EditContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Folder.
        /// </summary>
        internal static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Media Content.
        /// </summary>
        internal static string EditMediaContent {
            get {
                return ResourceManager.GetString("EditMediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Menu.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit message folder.
        /// </summary>
        internal static string EditMessageFolder {
            get {
                return ResourceManager.GetString("EditMessageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meta Data Field.
        /// </summary>
        internal static string EditMetaDataField {
            get {
                return ResourceManager.GetString("EditMetaDataField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Type.
        /// </summary>
        internal static string EditProfileType {
            get {
                return ResourceManager.GetString("EditProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Report Scheduler.
        /// </summary>
        internal static string EditReportScheduler {
            get {
                return ResourceManager.GetString("EditReportScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Step {0}.
        /// </summary>
        internal static string EditStepX {
            get {
                return ResourceManager.GetString("EditStepX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Taxonomy.
        /// </summary>
        internal static string EditTaxonomy {
            get {
                return ResourceManager.GetString("EditTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        internal static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditUser.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exception.
        /// </summary>
        internal static string ErrorException {
            get {
                return ResourceManager.GetString("ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        internal static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders List.
        /// </summary>
        internal static string FoldersList {
            get {
                return ResourceManager.GetString("FoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your folder template, are you sure you want to continue?.
        /// </summary>
        internal static string FolderTemplateNotFinished {
            get {
                return ResourceManager.GetString("FolderTemplateNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Fields.
        /// </summary>
        internal static string FormFields {
            get {
                return ResourceManager.GetString("FormFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        internal static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login into your account.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        internal static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Content.
        /// </summary>
        internal static string MediaContent {
            get {
                return ResourceManager.GetString("MediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Content List.
        /// </summary>
        internal static string MediaContentsList {
            get {
                return ResourceManager.GetString("MediaContentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Editor.
        /// </summary>
        internal static string MenuEditor {
            get {
                return ResourceManager.GetString("MenuEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu list.
        /// </summary>
        internal static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose folder to replace messages after deleting.
        /// </summary>
        internal static string MessageFolderReplaceAfterDelete {
            get {
                return ResourceManager.GetString("MessageFolderReplaceAfterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data.
        /// </summary>
        internal static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data Field Editor.
        /// </summary>
        internal static string MetaDataFieldEditor {
            get {
                return ResourceManager.GetString("MetaDataFieldEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data Fields List.
        /// </summary>
        internal static string MetaDataFieldsList {
            get {
                return ResourceManager.GetString("MetaDataFieldsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data fields list.
        /// </summary>
        internal static string MetaDataList {
            get {
                return ResourceManager.GetString("MetaDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new message folder.
        /// </summary>
        internal static string NewMessageFolder {
            get {
                return ResourceManager.GetString("NewMessageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Settings.
        /// </summary>
        internal static string PermissionSettings {
            get {
                return ResourceManager.GetString("PermissionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Explorer.
        /// </summary>
        internal static string ProcessExplorer {
            get {
                return ResourceManager.GetString("ProcessExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile permissions.
        /// </summary>
        internal static string ProfilePermissions {
            get {
                return ResourceManager.GetString("ProfilePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile type ditor.
        /// </summary>
        internal static string ProfileTypeEditor {
            get {
                return ResourceManager.GetString("ProfileTypeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Types List.
        /// </summary>
        internal static string ProfileTypeList {
            get {
                return ResourceManager.GetString("ProfileTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile types list.
        /// </summary>
        internal static string ProfileTypesList {
            get {
                return ResourceManager.GetString("ProfileTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your password.
        /// </summary>
        internal static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all version of this content or just this version?.
        /// </summary>
        internal static string RemoveContentWithVersions {
            get {
                return ResourceManager.GetString("RemoveContentWithVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this.
        /// </summary>
        internal static string RemoveQuestion {
            get {
                return ResourceManager.GetString("RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply {0}.
        /// </summary>
        internal static string ReplyX {
            get {
                return ResourceManager.GetString("ReplyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report definition editor.
        /// </summary>
        internal static string ReportDefinitionEditor {
            get {
                return ResourceManager.GetString("ReportDefinitionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report definitions.
        /// </summary>
        internal static string ReportDefinitionsList {
            get {
                return ResourceManager.GetString("ReportDefinitionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Preview.
        /// </summary>
        internal static string ReportPreview {
            get {
                return ResourceManager.GetString("ReportPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Scheduler Editor.
        /// </summary>
        internal static string ReportSchedulerEditor {
            get {
                return ResourceManager.GetString("ReportSchedulerEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Scheduler List.
        /// </summary>
        internal static string ReportSchedulerList {
            get {
                return ResourceManager.GetString("ReportSchedulerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain not saved.
        /// </summary>
        internal static string SaveApprovalChainError {
            get {
                return ResourceManager.GetString("SaveApprovalChainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this.
        /// </summary>
        internal static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status (Live).
        /// </summary>
        internal static string ServerDashboard {
            get {
                return ResourceManager.GetString("ServerDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Explorer.
        /// </summary>
        internal static string ServerDashboardProcessExplorer {
            get {
                return ResourceManager.GetString("ServerDashboardProcessExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull.
        /// </summary>
        internal static string Successfull {
            get {
                return ResourceManager.GetString("Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status (Live).
        /// </summary>
        internal static string SystemStatusLive {
            get {
                return ResourceManager.GetString("SystemStatusLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomies List.
        /// </summary>
        internal static string TaxonomiesList {
            get {
                return ResourceManager.GetString("TaxonomiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your alias and your taxonomy, are you sure you want to continue?.
        /// </summary>
        internal static string TaxonomyAliasNotFinished {
            get {
                return ResourceManager.GetString("TaxonomyAliasNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy Editor.
        /// </summary>
        internal static string TaxonomyEditor {
            get {
                return ResourceManager.GetString("TaxonomyEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy list.
        /// </summary>
        internal static string TaxonomyList {
            get {
                return ResourceManager.GetString("TaxonomyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t finish your taxonomy, are you sure you want to continue?.
        /// </summary>
        internal static string TaxonomyNotFinished {
            get {
                return ResourceManager.GetString("TaxonomyNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Editor.
        /// </summary>
        internal static string TemplateEditor {
            get {
                return ResourceManager.GetString("TemplateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates list.
        /// </summary>
        internal static string TemplatesList {
            get {
                return ResourceManager.GetString("TemplatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Editor.
        /// </summary>
        internal static string UserEditor {
            get {
                return ResourceManager.GetString("UserEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permissions.
        /// </summary>
        internal static string UserPermissions {
            get {
                return ResourceManager.GetString("UserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        internal static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Waning {
            get {
                return ResourceManager.GetString("Waning", resourceCulture);
            }
        }
    }
}
