//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.CMS.Administration.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.CMS.Administration.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/apple-touch-icon.png.
        /// </summary>
        internal static string AppleTouchIcon {
            get {
                return ResourceManager.GetString("AppleTouchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/favicon-16x16.png.
        /// </summary>
        internal static string Icon16x16 {
            get {
                return ResourceManager.GetString("Icon16x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/favicon-32x32.png.
        /// </summary>
        internal static string Icon32x32 {
            get {
                return ResourceManager.GetString("Icon32x32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/manifest.json.
        /// </summary>
        internal static string Manifest {
            get {
                return ResourceManager.GetString("Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/safari-pinned-tab.svg.
        /// </summary>
        internal static string MaskIcon {
            get {
                return ResourceManager.GetString("MaskIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmegaCMS.
        /// </summary>
        internal static string MDCMSAdministrationName {
            get {
                return ResourceManager.GetString("MDCMSAdministrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmegaCMS Administration.
        /// </summary>
        internal static string MDCMSAdministrationTitle {
            get {
                return ResourceManager.GetString("MDCMSAdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/browserconfig.xml.
        /// </summary>
        internal static string MsApplicationConfig {
            get {
                return ResourceManager.GetString("MsApplicationConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets/md-favicon-white-on-blue/favicon.ico.
        /// </summary>
        internal static string ShortcutIcon {
            get {
                return ResourceManager.GetString("ShortcutIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
    }
}
