//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.CMS.Installer.Hosted.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.CMS.Installer.Hosted.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administration.hosted.{2}.{0}-x64.{1}.7z.
        /// </summary>
        internal static string Artifact_Hosted_AdminFileFormat {
            get {
                return ResourceManager.GetString("Artifact_Hosted_AdminFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/administration.hosted/{1}.
        /// </summary>
        internal static string Artifact_Hosted_AdminFormat {
            get {
                return ResourceManager.GetString("Artifact_Hosted_AdminFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webapi.hosted.{2}.{0}-x64.{1}.7z.
        /// </summary>
        internal static string Artifact_Hosted_WebApiFileFormat {
            get {
                return ResourceManager.GetString("Artifact_Hosted_WebApiFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/webapi.hosted/{1}.
        /// </summary>
        internal static string Artifact_Hosted_WebApiFormat {
            get {
                return ResourceManager.GetString("Artifact_Hosted_WebApiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Administration.
        /// </summary>
        internal static string Artifact_Name_Admin {
            get {
                return ResourceManager.GetString("Artifact_Name_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Async Task Processor.
        /// </summary>
        internal static string Artifact_Name_AsyncTask {
            get {
                return ResourceManager.GetString("Artifact_Name_AsyncTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega WebApi.
        /// </summary>
        internal static string Artifact_Name_WebApi {
            get {
                return ResourceManager.GetString("Artifact_Name_WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://downloads.omegacms.io.
        /// </summary>
        internal static string Artifact_Url {
            get {
                return ResourceManager.GetString("Artifact_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linux.
        /// </summary>
        internal static string PlatformType_Linux {
            get {
                return ResourceManager.GetString("PlatformType_Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osx.
        /// </summary>
        internal static string PlatformType_Osx {
            get {
                return ResourceManager.GetString("PlatformType_Osx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win.
        /// </summary>
        internal static string PlatformType_Win {
            get {
                return ResourceManager.GetString("PlatformType_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        internal static string ReleaseType_Debug {
            get {
                return ResourceManager.GetString("ReleaseType_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release.
        /// </summary>
        internal static string ReleaseType_Release {
            get {
                return ResourceManager.GetString("ReleaseType_Release", resourceCulture);
            }
        }
    }
}
