/// <reference path="../../../globalVariables.ts"/>
/// <reference path="../../../helpers/mdException.ts" />
/// <reference path="../../../settings.ts" />
namespace mdBusinessLogic.dataAccess.controllers.base {
    /**
     * AjaxMethodData class
     * This class is used to send and receive data sent over standard http(s) protocols
     * @typeparam C Controller class type that is initiating the AjaxMethodData class
     * @typeparam E Entity class type that is being returned as part of the AjaxMethodData execution
     */
    export class AjaxMethodData<C, E extends entities.base.IBaseEntity<E>> {
        public responseData: E;
        public responseDataArray: Array<E>;
        public requestData: any;
        public controller: C;
        public exception: helpers.mdException;
        protected requestId: string;
        private requestIdAutoGenerated: boolean;
        constructor(requestId?: string) {
            this.responseData = null;
            this.requestData = null;
            this.controller = null;
            this.exception = null;
            this.responseDataArray = null;
            this.requestId = requestId !== undefined && requestId != null && requestId.trim().length > 0 ? requestId : helpers.Guid.create().toString();
            this.requestIdAutoGenerated = !(requestId !== undefined && requestId != null && requestId.trim().length > 0);
        }
        public getRequestId(): string {
            return this.requestId;
        }
        public getRequestIdAutoGenerated(): boolean {
            return this.requestIdAutoGenerated;
        }
    }

    /**
     * AjaxMethodDataSocket class
     * This class is used to send and receive data sent over the websocket protocol
     * @typeparam C Controller class type that is initiating the AjaxMethodDataSocket class
     * @typeparam E Entity class type that is being returned as part of the AjaxMethodDataSocket execution
     */
    export class AjaxMethodDataSocket<C, E extends entities.base.IBaseEntity<E>> extends AjaxMethodData<C, E> {
        public socket: WebSocket;
        constructor(requestId?: string) {
            super(requestId);
            this.socket = null;
        }
    }

    /**
     * AjaxMethodOptions class
     * Class used to setup the ajax request
     * @typeparam C Controller class type that is initiating the AjaxMethodOptions class
     * @typeparam E Entity class type that is being returned as part of the AjaxMethodOptions execution
     */
    export class AjaxMethodOptions<C, E extends entities.base.IBaseEntity<E>> extends AjaxMethodData<C, E> {
        public includeAuthHeader: boolean;
        public isJsonArray: boolean;
        public isAdministration: boolean;
        public isFormData: boolean;
        public contentType: AjaxMethodHeader;
        public dataType: string;
        public showLoading: boolean;
        public address: string;
        public clearCache: boolean;
        public method: AjaxMethodType;
        public headers: Array<AjaxMethodHeader>;
        public lcid: number;
        public onSuccess = this._onsuccess;
        public onClose = this._onClose;
        public onError = this._onerror;
        public isInitCall: boolean;

        constructor(requestId?: string) {
            super(requestId);
            this.includeAuthHeader = false;
            this.isJsonArray = false;
            this.isAdministration = mdBusinessLogic.settings.isAdministration;
            this.isFormData = false;
            this.contentType = null;
            this.showLoading = true;
            this.address = '';
            this.method = null;
            this.headers = new Array<AjaxMethodHeader>();
            this.lcid = mdBusinessLogic.settings.lcid;
            this.clearCache = false;
            this.isInitCall = false;
        }

        public getFullUrl(prefix: string = ''): string {
            return mdBusinessLogic.settings.apiBase + prefix + this.getAddressWithCacheFlag(this.address, this.clearCache);
        }

        private getAddressWithCacheFlag(address: string, clearCache: boolean): string {
            if (clearCache) {
                if (address[address.length - 1] != '/') {
                    address += '/';
                }
                if (address.indexOf('?') >= 0) {
                    address += '?';
                } else {
                    address += '&';
                }
                address += encodeURIComponent('_') + '=' + encodeURIComponent(new Date().getTime().toString());
            }
            return address;
        }

        public getPartialUrl(prefix: string = ''): string {
            let apiBase = mdBusinessLogic.settings.apiBase;
            if (apiBase[apiBase.length - 1] != mdBusinessLogic.settings.apiBaseSeparator) {
                apiBase = apiBase.substr(0, apiBase.length-1) + mdBusinessLogic.settings.apiBaseSeparator;
            }
            return apiBase + prefix;
        }

        public getMethodTypeString(): string {
            switch (this.method) {
                case AjaxMethodType.GET:
                    return 'GET';
                case AjaxMethodType.POST:
                    return 'POST';
                case AjaxMethodType.PUT:
                    return 'PUT';
                case AjaxMethodType.DELETE:
                    return 'DELETE';
                case AjaxMethodType.SOCKET:
                    return 'SOCKET';
            }
        }

        private _onsuccess(data: AjaxMethodData<C, E>): void {

        }

        private _onClose(data: AjaxMethodData<C, E>): void {

        }

        private _onerror(data: AjaxMethodData<C, E>): void {

        }

        public getRequestId(): string {
            if (super.getRequestIdAutoGenerated() && this.method != AjaxMethodType.SOCKET) {
                this.requestId = '';
                return mdBusinessLogic.helpers.crypto.md5(JSON.stringify(this));
            }
            return super.getRequestId();
        }
    }

    export enum AjaxMethodType {
        GET = 1,
        POST = 2,
        PUT = 3,
        DELETE = 4,
        SOCKET = 5
    }

    export class AjaxMethodHeader {
        public name: string = '';
        public value: string = '';
        public constructor(name: string, value: string) {
            this.name = name;
            this.value = value;
        }
    }
}