<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MD.CMS.Template</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Global.asax.cs" />
    <Compile Remove="Models\**" />
    <Compile Remove="Properties\**" />
    <Compile Remove="Resources\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="modern-app\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Web.config" />
    <Content Remove="Web.Debug.config" />
    <Content Remove="Web.Release.config" />
    <Content Remove="packages.config" />
    <Content Remove="Global.asax" />
  </ItemGroup>
</Project>
